language: php

php:
    - 5.4


before_script:
- wget -nc http://getcomposer.org/composer.phar
- php composer.phar install --dev

script: phpunit --coverage-text

notifications: [ email: [ zetaweb@gmail.com ] ]